/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Hafidz
 */
   
public class BiodataDokter extends javax.swing.JFrame {
    private String namaDokter;
    private String rumahSakit;
    private String nomorTelepon;
    private int biaya;
   
    
    public BiodataDokter(String namaDokter, String rumahSakit, String nomorTelepon, int par) {
        initComponents();
        this.namaDokter = namaDokter;
        this.rumahSakit = rumahSakit;
        this.nomorTelepon = nomorTelepon;
        
        NamaDokter.setText("Nama Dokter: " + namaDokter);
        RumahSakit.setText("Rumah Sakit: " + rumahSakit);
        NomorTelepon.setText("Nomor Telepon: " + nomorTelepon);
        
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        Biaya.setText("Biaya: " + currencyFormat.format(biaya));
    }

    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TombolBackToLogin = new javax.swing.JButton();
        Biaya = new javax.swing.JLabel();
        NomorTelepon = new javax.swing.JLabel();
        RumahSakit = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 120, 40));

        Biaya.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Biaya.setForeground(new java.awt.Color(255, 255, 255));
        Biaya.setText("nama dokter");
        getContentPane().add(Biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 590, -1));

        NomorTelepon.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NomorTelepon.setForeground(new java.awt.Color(255, 255, 255));
        NomorTelepon.setText("nama dokter");
        getContentPane().add(NomorTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 680, -1));

        RumahSakit.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        RumahSakit.setForeground(new java.awt.Color(255, 255, 255));
        RumahSakit.setText("nama dokter");
        getContentPane().add(RumahSakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 530, 20));

        NamaDokter.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NamaDokter.setForeground(new java.awt.Color(255, 255, 255));
        NamaDokter.setText("nama dokter");
        getContentPane().add(NamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 690, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/7[1].png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        PilihanDokter login = new PilihanDokter();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataDokter("", "", "", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Biaya;
    private javax.swing.JLabel NamaDokter;
    private javax.swing.JLabel NomorTelepon;
    private javax.swing.JLabel RumahSakit;
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
