/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author Hafidz
 */
public class HalamanDokter extends javax.swing.JFrame {
 
    private final String spesialis;
    private final int biaya;

    public HalamanDokter(String spesialis, int biaya) {
        this.spesialis = spesialis;
        this.biaya = biaya;
        
        
    /**
     * Creates new form TampilanPasien
     */
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Biaya = new JLabel("Biaya: " + biaya);
        Spesialis = new JLabel("Spesialis: " + spesialis);
        BtnPembayaran = new JButton("Bayar");
        TombolBackToLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Biaya.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Biaya.setForeground(new java.awt.Color(255, 255, 255));
        Biaya.setText("Biaya");
        getContentPane().add(Biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 240, -1));

        Spesialis.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Spesialis.setForeground(new java.awt.Color(255, 255, 255));
        Spesialis.setText("Spesialis");
        getContentPane().add(Spesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, -1));

        BtnPembayaran.setBackground(new java.awt.Color(63, 111, 253));
        BtnPembayaran.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        BtnPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        BtnPembayaran.setText("Bayar");
        BtnPembayaran.setBorder(null);
        BtnPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 120, 50));

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/8[1].png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        PilihanDokter login = new PilihanDokter();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    private void BtnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPembayaranActionPerformed
        // TODO add your handling code here:
        PilihanDokter sukses = new PilihanDokter();
        sukses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPembayaranActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDokter("Spesialis Kulit", 500000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Biaya;
    private javax.swing.JButton BtnPembayaran;
    private javax.swing.JLabel Spesialis;
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
