/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

/**
 *
 * @author Hafidz
 */
public class InformasiAwal extends javax.swing.JFrame {
  
    /**
     * Creates new form InformasiAwal
     */
    public InformasiAwal() {
        initComponents();
    }

    public static InformasiAwal getInstance() {
        Object instance = null;
        if (instance == null) {
            instance = new InformasiAwal();
        }
        return (InformasiAwal) instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TombolMulai = new javax.swing.JButton();
        DesignInformasiAwal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TombolMulai.setBackground(new java.awt.Color(63, 111, 253));
        TombolMulai.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolMulai.setForeground(new java.awt.Color(255, 255, 255));
        TombolMulai.setText("Mulai");
        TombolMulai.setBorder(null);
        TombolMulai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMulaiActionPerformed(evt);
            }
        });
        getContentPane().add(TombolMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 190, 60));

        DesignInformasiAwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/DOC DIRECT (3) (1).png"))); // NOI18N
        DesignInformasiAwal.setLabelFor(this);
        DesignInformasiAwal.setMaximumSize(new java.awt.Dimension(1100, 619));
        DesignInformasiAwal.setMinimumSize(new java.awt.Dimension(1100, 619));
        getContentPane().add(DesignInformasiAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMulaiActionPerformed
        // TODO add your handling code here:
        LoginPasienDanDokter form2 = new LoginPasienDanDokter();
        form2.setVisible(true);
        // Menutup Form1
        this.dispose();
    }//GEN-LAST:event_TombolMulaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformasiAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InformasiAwal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DesignInformasiAwal;
    private javax.swing.JButton TombolMulai;
    // End of variables declaration//GEN-END:variables
}
