/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hafidz
 */
public class LoginPasien extends javax.swing.JFrame {

    /**
     * Creates new form LoginPasien
     */
    public LoginPasien() {
        initComponents();
    }
public static LoginPasien getInstance() {
        Object instance = null;
        if (instance == null) {
            instance = new LoginPasien();
        }
        return (LoginPasien) instance;
}
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputEmail2 = new javax.swing.JTextField();
        TombolLogin2 = new javax.swing.JButton();
        TombolRegister1 = new javax.swing.JButton();
        InputPassword2 = new javax.swing.JTextField();
        TombolBack2 = new javax.swing.JButton();
        Pasien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputEmail2.setBackground(new java.awt.Color(63, 111, 253));
        InputEmail2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        InputEmail2.setForeground(new java.awt.Color(255, 255, 255));
        InputEmail2.setText("Email");
        InputEmail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputEmail2MouseClicked(evt);
            }
        });
        InputEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmail2ActionPerformed(evt);
            }
        });
        getContentPane().add(InputEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 270, 40));

        TombolLogin2.setBackground(new java.awt.Color(63, 111, 253));
        TombolLogin2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TombolLogin2.setForeground(new java.awt.Color(255, 255, 255));
        TombolLogin2.setText("Login");
        TombolLogin2.setBorder(null);
        TombolLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolLogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 140, 40));

        TombolRegister1.setBackground(new java.awt.Color(63, 111, 253));
        TombolRegister1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TombolRegister1.setForeground(new java.awt.Color(255, 255, 255));
        TombolRegister1.setText("Register");
        TombolRegister1.setBorder(null);
        TombolRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolRegister1ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 130, 40));

        InputPassword2.setBackground(new java.awt.Color(63, 111, 253));
        InputPassword2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        InputPassword2.setForeground(new java.awt.Color(255, 255, 255));
        InputPassword2.setText("Password");
        InputPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputPassword2MouseClicked(evt);
            }
        });
        InputPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPassword2ActionPerformed(evt);
            }
        });
        getContentPane().add(InputPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 270, 40));

        TombolBack2.setBackground(new java.awt.Color(63, 111, 253));
        TombolBack2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBack2.setForeground(new java.awt.Color(255, 255, 255));
        TombolBack2.setText("Back");
        TombolBack2.setBorder(null);
        TombolBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBack2ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 110, 40));

        Pasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/DOC DIRECT (6) (1).png"))); // NOI18N
        Pasien.setText("Pasien");
        Pasien.setPreferredSize(new java.awt.Dimension(1100, 619));
        getContentPane().add(Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean cekKredensial(String email, String password) {
    String SUrl = "jdbc:MySQL://localhost:3306/pasiendb";
    String SUser = "root";
    String SPass = "";
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
        Statement st = con.createStatement();
        String query = "SELECT * FROM user WHERE Email= '" + email + "'";
        ResultSet rs = (ResultSet) st.executeQuery(query);
        while (rs.next()) {
            String passDb = rs.getString("Password");
            if (password.equals(passDb)) {
                return true;
            }
        }
    } catch (Exception e) {
        System.out.println("Error!" + e.getMessage());
    }
    return false;
}
    private void InputEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmail2ActionPerformed
        // TODO add your handling code here:
    String email = InputEmail2.getText();
    String password = InputPassword2.getText();

    // Misalkan Anda memiliki metode untuk memeriksa kecocokan email dan password
    boolean berhasilLogin = cekKredensial(email, password);

    if (berhasilLogin) {
        // Jika login berhasil, pindahkan ke halaman berikutnya
        TampilanPasien formBerikutnya = new TampilanPasien();
        formBerikutnya.setVisible(true);
        this.dispose();
    } else {
        // Jika login gagal, tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Email atau Password Salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
    }
           
    }//GEN-LAST:event_InputEmail2ActionPerformed

    private void TombolLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolLogin2ActionPerformed
        // TODO add your handling code here:
        String  Email, Password, fullName = null, passDb = null;
        String SUrl, SUser, SPass;
            SUrl = "jdbc:MySQL://localhost:3306/pasiendb";
            SUser = "root";
            SPass = "";
            int notFound = 0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =  DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
    
            if("".equals(InputEmail2.getText())){
                 JOptionPane.showMessageDialog(new JFrame(), "Masukan Email Anda", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(InputPassword2.getText())){
                 JOptionPane.showMessageDialog(new JFrame(), "Masukan Password Anda", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else{
                Email = InputEmail2.getText();
                Password = InputPassword2.getText();
                
                String query = "SELECT * FROM user WHERE Email= '"+Email+"'";
       
                java.sql.ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                passDb = rs.getString("Password");    
                fullName = rs.getString("Nama");
                notFound = 1;
            }
            if(notFound == 1 && Password.equals(passDb)){
                TampilanPasien TampilanPasien = new TampilanPasien();
                TampilanPasien.setUser(fullName);
                TampilanPasien.setVisible(true);
                TampilanPasien.pack();
                TampilanPasien.setLocationRelativeTo(null); 
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(new JFrame(), "Email atau Password Salah!", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            InputPassword2.setText("");
            
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        }
    }//GEN-LAST:event_TombolLogin2ActionPerformed

    private void TombolRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolRegister1ActionPerformed
        // TODO add your handling code here:
        Register formPendaftaran = new Register();
        formPendaftaran.setVisible(true);
        formPendaftaran.pack();
        formPendaftaran.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_TombolRegister1ActionPerformed

    private void InputPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPassword2ActionPerformed

    private void TombolBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBack2ActionPerformed
        // TODO add your handling code here:
    LoginPasienDanDokter login = new LoginPasienDanDokter();
    login.setVisible(true);
    this.dispose();                            
    }//GEN-LAST:event_TombolBack2ActionPerformed

    private void InputEmail2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputEmail2MouseClicked
        // TODO add your handling code here:
        InputEmail2.setText("");
    }//GEN-LAST:event_InputEmail2MouseClicked

    private void InputPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputPassword2MouseClicked
        // TODO add your handling code here:
        InputPassword2.setText("");
    }//GEN-LAST:event_InputPassword2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputEmail2;
    private javax.swing.JTextField InputPassword2;
    private javax.swing.JLabel Pasien;
    private javax.swing.JButton TombolBack2;
    private javax.swing.JButton TombolLogin2;
    private javax.swing.JButton TombolRegister1;
    // End of variables declaration//GEN-END:variables

   

    private static class ResultSet {

        public ResultSet() {
        }

        private boolean next() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private String getString(String Password) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
