/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

/**
 *
 * @author Hafidz
 */
public class LoginPasienDanDokter extends javax.swing.JFrame {

    /**
     * Creates new form LoginPasienDanDokter
     */
    public LoginPasienDanDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TblLoginDokter = new javax.swing.JButton();
        TblLoginPasien = new javax.swing.JButton();
        TombolBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblLoginDokter.setBackground(new java.awt.Color(63, 111, 253));
        TblLoginDokter.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TblLoginDokter.setForeground(new java.awt.Color(255, 255, 255));
        TblLoginDokter.setText("Login Dokter");
        TblLoginDokter.setBorder(null);
        TblLoginDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblLoginDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblLoginDokterActionPerformed(evt);
            }
        });
        getContentPane().add(TblLoginDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, 50));

        TblLoginPasien.setBackground(new java.awt.Color(63, 111, 253));
        TblLoginPasien.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TblLoginPasien.setForeground(new java.awt.Color(255, 255, 255));
        TblLoginPasien.setText("Login Pasien");
        TblLoginPasien.setBorder(null);
        TblLoginPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblLoginPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblLoginPasienActionPerformed(evt);
            }
        });
        getContentPane().add(TblLoginPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 220, 50));

        TombolBack1.setBackground(new java.awt.Color(63, 111, 253));
        TombolBack1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBack1.setForeground(new java.awt.Color(255, 255, 255));
        TombolBack1.setText("Back");
        TombolBack1.setBorder(null);
        TombolBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/2[1].png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1100, 619));
        jLabel1.setMinimumSize(new java.awt.Dimension(1100, 619));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBack1ActionPerformed
        // TODO add your handling code here:
        InformasiAwal login = new InformasiAwal();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TombolBack1ActionPerformed

    private void TblLoginPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblLoginPasienActionPerformed
        // TODO add your handling code here:
        LoginPasien formPendaftaran = new LoginPasien();
        formPendaftaran.setVisible(true);
        formPendaftaran.pack();
        formPendaftaran.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_TblLoginPasienActionPerformed

    private void TblLoginDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblLoginDokterActionPerformed
        // TODO add your handling code here:
        LoginDokter formPendaftaran = new LoginDokter();
        formPendaftaran.setVisible(true);
        formPendaftaran.pack();
        formPendaftaran.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_TblLoginDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPasienDanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPasienDanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPasienDanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPasienDanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPasienDanDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TblLoginDokter;
    private javax.swing.JButton TblLoginPasien;
    private javax.swing.JButton TombolBack1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
