/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Hafidz
 */
public class Pembayaran extends javax.swing.JFrame {
    
    private String namaDokter;
    private String rumahSakit;
    private String nomorTelepon;
    private int biaya;
    
    
    public Pembayaran(String namaDokter, String rumahSakit, String nomorTelepon, int biaya) {
        initComponents();
        this.namaDokter = namaDokter;
        this.rumahSakit = rumahSakit;
        this.nomorTelepon = nomorTelepon;
        this.biaya = biaya;
        
        NamaDokter.setText("Nama Dokter: " + namaDokter);
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        Biaya.setText("Biaya: " + currencyFormat.format(biaya));
        
    /**
     * Creates new form TampilanPasien
     */
  
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BayarSekarang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Biaya = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JLabel();
        TombolBackToLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BayarSekarang.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BayarSekarang.setForeground(new java.awt.Color(63, 111, 253));
        BayarSekarang.setText("Bayar Sekarang");
        BayarSekarang.setBorder(null);
        BayarSekarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BayarSekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarSekarangActionPerformed(evt);
            }
        });
        getContentPane().add(BayarSekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 150, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Biaya.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Biaya.setForeground(new java.awt.Color(255, 255, 255));
        Biaya.setText("Biaya");
        getContentPane().add(Biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 430, -1));

        NamaDokter.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NamaDokter.setForeground(new java.awt.Color(255, 255, 255));
        NamaDokter.setText("nama dokter");
        getContentPane().add(NamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 580, -1));

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/8[1].png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        PilihanDokter login = new PilihanDokter();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    private void BayarSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarSekarangActionPerformed
        JOptionPane.showMessageDialog(this, "Pembayaran berhasil!");
        BiodataDokter formBiodata = new BiodataDokter(namaDokter, rumahSakit, nomorTelepon, biaya);
        formBiodata.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BayarSekarangActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran("", "", "", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarSekarang;
    private javax.swing.JLabel Biaya;
    private javax.swing.JLabel NamaDokter;
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
