/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

/**
 *
 * @author Hafidz
 */
public class PilihanDokter extends javax.swing.JFrame {
    
    public PilihanDokter() {
       
        initComponents();
    /**
     * Creates new form TampilanPasien
     */
  
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dokter6 = new javax.swing.JButton();
        Dokter5 = new javax.swing.JButton();
        Dokter4 = new javax.swing.JButton();
        Dokter3 = new javax.swing.JButton();
        Dokter2 = new javax.swing.JButton();
        Dokter1 = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        TombolBackToLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dokter6.setBackground(new java.awt.Color(63, 111, 253));
        Dokter6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter6.setForeground(new java.awt.Color(255, 255, 255));
        Dokter6.setText("Spesialis Gigi");
        Dokter6.setBorder(null);
        Dokter6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter6ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 120, 30));

        Dokter5.setBackground(new java.awt.Color(63, 111, 253));
        Dokter5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter5.setForeground(new java.awt.Color(255, 255, 255));
        Dokter5.setText("Spesialis Syaraf");
        Dokter5.setBorder(null);
        Dokter5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter5ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 120, 30));

        Dokter4.setBackground(new java.awt.Color(63, 111, 253));
        Dokter4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter4.setForeground(new java.awt.Color(255, 255, 255));
        Dokter4.setText("Dokter Umum");
        Dokter4.setBorder(null);
        Dokter4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter4ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 120, 30));

        Dokter3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter3.setForeground(new java.awt.Color(63, 111, 253));
        Dokter3.setText("Spesialis Gizi");
        Dokter3.setBorder(null);
        Dokter3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter3ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 120, 30));

        Dokter2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter2.setForeground(new java.awt.Color(63, 111, 253));
        Dokter2.setText("Spesialis Jantung");
        Dokter2.setBorder(null);
        Dokter2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter2ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 120, 30));

        Dokter1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Dokter1.setForeground(new java.awt.Color(63, 111, 253));
        Dokter1.setText("Spesialis Kulit");
        Dokter1.setBorder(null);
        Dokter1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dokter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dokter1ActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 120, 30));

        user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("nama");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/DOC DIRECT (9) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        TampilanPasien login = new TampilanPasien();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    private void Dokter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter1ActionPerformed
        // TODO add your handling code here:
        String NamaDokter = "dr. Adi Agung Anantawijaya Daryago, Sp.DV";
        String rumahSakit = "RS Sentosa";
        String nomorTelepon = "+6281234567890";
        int biaya = (int) 50000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Dokter1ActionPerformed

    private void Dokter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter2ActionPerformed
        // TODO add your handling code here:
        String NamaDokter = "dr. Adhantoro Rahadyan Sp.JP, FIHA";
        String rumahSakit = "RS Mitra Keluarga";
        String nomorTelepon = "+6285812345678";
        int biaya = (int) 60000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Dokter2ActionPerformed

    private void Dokter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter3ActionPerformed
        // TODO add your handling code here:
        String NamaDokter = "dr. Ekky M. Rahardja, Sp.GK";
        String rumahSakit = "Bali International Medical Center (BIMC) Hospitals";
        String nomorTelepon = "+6282312366678";
        int biaya = (int) 50000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Dokter3ActionPerformed

    private void Dokter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter4ActionPerformed
        // TODO add your handling code here:
        String NamaDokter = "dr. Ariel Tatum";
        String rumahSakit = "RSPI Pondok Indah";
        String nomorTelepon = "+6282344566678";
        int biaya = (int) 30000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Dokter4ActionPerformed

    private void Dokter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter5ActionPerformed
        // TODO add your handling code here:
        String NamaDokter = "dr. Maria Ardelia Purwaningrum Sp.S";
        String rumahSakit = "RS Premier Jatinegara";
        String nomorTelepon = "+6282322366678";
        int biaya = (int) 50000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
                        
    }//GEN-LAST:event_Dokter5ActionPerformed

    private void Dokter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dokter6ActionPerformed
        // TODO add your handling code here:
            String NamaDokter = "drg. Andrew, Sp.Perio";
        String rumahSakit = "RS Harapan Kita";
        String nomorTelepon = "+6284577766678";
        int biaya = (int) 50000;
        
        Pembayaran formPembayaran = new Pembayaran(NamaDokter, rumahSakit, nomorTelepon, biaya);
        formPembayaran.setVisible(true);
        this.dispose();
                     
    }//GEN-LAST:event_Dokter6ActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihanDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dokter1;
    private javax.swing.JButton Dokter2;
    private javax.swing.JButton Dokter3;
    private javax.swing.JButton Dokter4;
    private javax.swing.JButton Dokter5;
    private javax.swing.JButton Dokter6;
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
