/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

/**
 *
 * @author Hafidz
 */
public class ResepObat extends javax.swing.JFrame {

    /**
     * Creates new form TampilanPasien
     */
    public ResepObat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TombolBackToLogin = new javax.swing.JButton();
        DOkter9 = new javax.swing.JTextField();
        DOkter8 = new javax.swing.JTextField();
        DOkter7 = new javax.swing.JTextField();
        DOkter6 = new javax.swing.JTextField();
        DOkter5 = new javax.swing.JTextField();
        DOkter4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DOkter3 = new javax.swing.JTextField();
        DOkter2 = new javax.swing.JTextField();
        DOkter1 = new javax.swing.JTextField();
        DOkter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 120, 40));

        DOkter9.setBackground(new java.awt.Color(63, 111, 253));
        DOkter9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter9.setForeground(new java.awt.Color(255, 255, 255));
        DOkter9.setText("Umur");
        DOkter9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOkter9MouseClicked(evt);
            }
        });
        DOkter9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter9ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 190, 30));

        DOkter8.setBackground(new java.awt.Color(63, 111, 253));
        DOkter8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter8.setForeground(new java.awt.Color(255, 255, 255));
        DOkter8.setText("Nama Pasien");
        DOkter8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOkter8MouseClicked(evt);
            }
        });
        DOkter8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter8ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 190, 30));

        DOkter7.setBackground(new java.awt.Color(63, 111, 253));
        DOkter7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter7.setForeground(new java.awt.Color(255, 255, 255));
        DOkter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter7ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 590, 30));

        DOkter6.setBackground(new java.awt.Color(63, 111, 253));
        DOkter6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter6.setForeground(new java.awt.Color(255, 255, 255));
        DOkter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter6ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 590, 30));

        DOkter5.setBackground(new java.awt.Color(63, 111, 253));
        DOkter5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter5.setForeground(new java.awt.Color(255, 255, 255));
        DOkter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter5ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 590, 30));

        DOkter4.setBackground(new java.awt.Color(63, 111, 253));
        DOkter4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter4.setForeground(new java.awt.Color(255, 255, 255));
        DOkter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter4ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 590, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("List Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 70, -1));

        DOkter3.setBackground(new java.awt.Color(63, 111, 253));
        DOkter3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter3.setForeground(new java.awt.Color(255, 255, 255));
        DOkter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter3ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 590, 30));

        DOkter2.setBackground(new java.awt.Color(63, 111, 253));
        DOkter2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter2.setForeground(new java.awt.Color(255, 255, 255));
        DOkter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter2ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 590, 30));

        DOkter1.setBackground(new java.awt.Color(63, 111, 253));
        DOkter1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter1.setForeground(new java.awt.Color(255, 255, 255));
        DOkter1.setText("Tanggal");
        DOkter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOkter1MouseClicked(evt);
            }
        });
        DOkter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkter1ActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, 30));

        DOkter.setBackground(new java.awt.Color(63, 111, 253));
        DOkter.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DOkter.setForeground(new java.awt.Color(255, 255, 255));
        DOkter.setText("Dokter");
        DOkter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOkterMouseClicked(evt);
            }
        });
        DOkter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOkterActionPerformed(evt);
            }
        });
        getContentPane().add(DOkter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/DOC DIRECT (12) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        TampilanDokter login = new TampilanDokter();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    private void DOkterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkterActionPerformed

    private void DOkter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter1ActionPerformed

    private void DOkter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter2ActionPerformed

    private void DOkter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter3ActionPerformed

    private void DOkter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter4ActionPerformed

    private void DOkter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter5ActionPerformed

    private void DOkter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter6ActionPerformed

    private void DOkter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter7ActionPerformed

    private void DOkter8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter8ActionPerformed

    private void DOkter9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOkter9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOkter9ActionPerformed

    private void DOkterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOkterMouseClicked
        // TODO add your handling code here:
        DOkter.setText("");
    }//GEN-LAST:event_DOkterMouseClicked

    private void DOkter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOkter1MouseClicked
        // TODO add your handling code here:
        DOkter1.setText("");
    }//GEN-LAST:event_DOkter1MouseClicked

    private void DOkter8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOkter8MouseClicked
        // TODO add your handling code here:
        DOkter8.setText("");
    }//GEN-LAST:event_DOkter8MouseClicked

    private void DOkter9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOkter9MouseClicked
        // TODO add your handling code here:
        DOkter9.setText("");
    }//GEN-LAST:event_DOkter9MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOkter;
    private javax.swing.JTextField DOkter1;
    private javax.swing.JTextField DOkter2;
    private javax.swing.JTextField DOkter3;
    private javax.swing.JTextField DOkter4;
    private javax.swing.JTextField DOkter5;
    private javax.swing.JTextField DOkter6;
    private javax.swing.JTextField DOkter7;
    private javax.swing.JTextField DOkter8;
    private javax.swing.JTextField DOkter9;
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
