/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docdirect;

/**
 *
 * @author Hafidz
 */
public class TampilanPasien extends javax.swing.JFrame {

    /**
     * Creates new form TampilanPasien
     */
    public TampilanPasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        TombolBackToLogin = new javax.swing.JButton();
        pilihDokter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(63, 111, 253));
        user.setText("nama");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));

        TombolBackToLogin.setBackground(new java.awt.Color(63, 111, 253));
        TombolBackToLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TombolBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        TombolBackToLogin.setText("Back");
        TombolBackToLogin.setBorder(null);
        TombolBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TombolBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 120, 40));

        pilihDokter.setBackground(new java.awt.Color(63, 111, 253));
        pilihDokter.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        pilihDokter.setForeground(new java.awt.Color(255, 255, 255));
        pilihDokter.setText("Konsultasi dengan Dokter ");
        pilihDokter.setBorder(null);
        pilihDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pilihDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihDokterActionPerformed(evt);
            }
        });
        getContentPane().add(pilihDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 260, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/docdirect/5[1].png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackToLoginActionPerformed
        // TODO add your handling code here:
        LoginPasienDanDokter login = new LoginPasienDanDokter();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TombolBackToLoginActionPerformed

    private void pilihDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihDokterActionPerformed
        // TODO add your handling code here:
        PilihanDokter form2 = new PilihanDokter();
        form2.setVisible(true);
        // Menutup Form1
        this.dispose();
    }//GEN-LAST:event_pilihDokterActionPerformed

    public void setUser(String Nama){
            user.setText(Nama);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombolBackToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pilihDokter;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
